# Based on 23.04.
FROM nvcr.io/nvidia/pytorch:23.04-py3

# Python packages
COPY requirements-dev.txt /tmp/
RUN pip install -r /tmp/requirements-dev.txt

# Remove prevous TRT installation
RUN apt-get remove --purge -y libnvinfer* tensorrt*
RUN pip uninstall -y tensorrt

# Download & install internal TRT release

# Download TensorRT-9.0.0.2.Linux.x86_64-gnu.cuda-12.2.tar.gz to pwd before building docker image
# MD5sum is: fd601a5b112cb350d46a84a08017d500  TensorRT-9.0.0.2.Linux.x86_64-gnu.cuda-12.2.tar.gz

COPY TensorRT-9.0.0.2.Linux.x86_64-gnu.cuda-12.2.tar.gz /workspace/
RUN tar -xvf /workspace/TensorRT-9.0.0.2.Linux.x86_64-gnu.cuda-12.2.tar.gz -C /usr/local/
RUN pip install /usr/local/TensorRT-9.0.0.2/python/tensorrt-9.0.0-cp38-none-linux_x86_64.whl && rm -fr /workspace/TensorRT-9.0.0.2.Linux.x86_64-gnu.cuda-12.2.tar.gz
ENV LD_LIBRARY_PATH=/usr/local/TensorRT-9.0.0.2/lib/:$LD_LIBRARY_PATH

# Install Polygraphy v0.48.1.

COPY polygraphy-0.48.1-py2.py3-none-any.whl /workspace/
RUN pip uninstall -y polygraphy
RUN pip install /workspace/polygraphy-0.48.1-py2.py3-none-any.whl && rm -f /workspace/polygraphy-0.48.1-py2.py3-none-any.whl 

